// 球队名称中英文映射表
// 用于将 OpenFootball.json 中的英文球队名翻译为中文

const teamNameMap = {
  // ========== 英超 Premier League ==========
  'Manchester City': '曼城',
  'Manchester City FC': '曼城',
  'Man City': '曼城',
  'Arsenal': '阿森纳',
  'Arsenal FC': '阿森纳',
  'Liverpool': '利物浦',
  'Liverpool FC': '利物浦',
  'Aston Villa': '阿斯顿维拉',
  'Aston Villa FC': '阿斯顿维拉',
  'Tottenham Hotspur': '托特纳姆热刺',
  'Tottenham': '托特纳姆热刺',
  'Spurs': '托特纳姆热刺',
  'Manchester United': '曼联',
  'Manchester United FC': '曼联',
  'Man United': '曼联',
  'Man Utd': '曼联',
  'West Ham United': '西汉姆联',
  'West Ham': '西汉姆联',
  'Chelsea': '切尔西',
  'Chelsea FC': '切尔西',
  'Newcastle United': '纽卡斯尔联',
  'Newcastle': '纽卡斯尔联',
  'Newcastle Utd': '纽卡斯尔联',
  'Brighton & Hove Albion': '布莱顿',
  'Brighton': '布莱顿',
  'Brighton & Hove': '布莱顿',
  'Brighton and Hove Albion': '布莱顿',
  'Wolverhampton Wanderers': '狼队',
  'Wolves': '狼队',
  'Wolverhampton': '狼队',
  'Fulham': '富勒姆',
  'Fulham FC': '富勒姆',
  'Bournemouth': '伯恩茅斯',
  'AFC Bournemouth': '伯恩茅斯',
  'Crystal Palace': '水晶宫',
  'Brentford': '布伦特福德',
  'Brentford FC': '布伦特福德',
  'Everton': '埃弗顿',
  'Everton FC': '埃弗顿',
  'Nottingham Forest': '诺丁汉森林',
  "Nott'm Forest": '诺丁汉森林',
  'Luton Town': '卢顿',
  'Luton': '卢顿',
  'Burnley': '伯恩利',
  'Burnley FC': '伯恩利',
  'Sheffield United': '谢菲尔德联',
  'Sheffield Utd': '谢菲尔德联',
  'Sheffield U': '谢菲尔德联',
  'Leicester City': '莱斯特城',
  'Leicester': '莱斯特城',
  'Leeds United': '利兹联',
  'Leeds': '利兹联',
  'Leeds Utd': '利兹联',
  'Southampton': '南安普顿',
  'Southampton FC': '南安普顿',
  'Watford': '沃特福德',
  'Watford FC': '沃特福德',
  'Norwich City': '诺维奇',
  'Norwich': '诺维奇',
  'Ipswich Town': '伊普斯维奇',
  'Ipswich': '伊普斯维奇',
  'Queens Park Rangers': '女王公园巡游者',
  'QPR': '女王公园巡游者',
  'Reading': '雷丁',
  'Reading FC': '雷丁',
  'Stoke City': '斯托克城',
  'Stoke': '斯托克城',
  'Swansea City': '斯旺西',
  'Swansea': '斯旺西',
  'West Bromwich Albion': '西布罗姆维奇',
  'West Brom': '西布罗姆维奇',
  'West Bromwich': '西布罗姆维奇',
  'WBA': '西布罗姆维奇',
  'Huddersfield Town': '哈德斯菲尔德',
  'Huddersfield': '哈德斯菲尔德',
  'Cardiff City': '卡迪夫城',
  'Cardiff': '卡迪夫城',
  'Middlesbrough': '米德尔斯堡',
  'Sunderland': '桑德兰',
  'Hull City': '赫尔城',
  'Blackburn Rovers': '布莱克本',
  'Bolton Wanderers': '博尔顿',
  'Wigan Athletic': '维冈竞技',
  'Portsmouth': '朴茨茅斯',

  // ========== 德甲 Bundesliga ==========
  'Bayern München': '拜仁慕尼黑',
  'Bayern Munich': '拜仁慕尼黑',
  'FC Bayern München': '拜仁慕尼黑',
  'Borussia Dortmund': '多特蒙德',
  'Dortmund': '多特蒙德',
  'RB Leipzig': '莱比锡红牛',
  'RasenBallsport Leipzig': '莱比锡红牛',
  'Union Berlin': '柏林联合',
  '1. FC Union Berlin': '柏林联合',
  'SC Freiburg': '弗赖堡',
  'Freiburg': '弗赖堡',
  'Bayer Leverkusen': '勒沃库森',
  'Bayer 04 Leverkusen': '勒沃库森',
  'Leverkusen': '勒沃库森',
  'Eintracht Frankfurt': '法兰克福',
  'Frankfurt': '法兰克福',
  'VfL Wolfsburg': '沃尔夫斯堡',
  'Wolfsburg': '沃尔夫斯堡',
  'Mainz 05': '美因茨',
  'Mainz': '美因茨',
  '1. FSV Mainz 05': '美因茨',
  'Borussia Mönchengladbach': '门兴格拉德巴赫',
  "Borussia M'gladbach": '门兴格拉德巴赫',
  'Gladbach': '门兴格拉德巴赫',
  'FC Köln': '科隆',
  '1. FC Köln': '科隆',
  'Cologne': '科隆',
  'Hoffenheim': '霍芬海姆',
  'TSG Hoffenheim': '霍芬海姆',
  'Werder Bremen': '云达不莱梅',
  'Bremen': '云达不莱梅',
  'SV Werder Bremen': '云达不莱梅',
  'VfL Bochum': '波鸿',
  'Bochum': '波鸿',
  'FC Augsburg': '奥格斯堡',
  'Augsburg': '奥格斯堡',
  'VfB Stuttgart': '斯图加特',
  'Stuttgart': '斯图加特',
  'Hertha BSC': '柏林赫塔',
  'Hertha Berlin': '柏林赫塔',
  'Schalke 04': '沙尔克04',
  'FC Schalke 04': '沙尔克04',
  'Schalke': '沙尔克04',
  'Arminia Bielefeld': '比勒费尔德',
  'Bielefeld': '比勒费尔德',
  'Greuther Fürth': '菲尔特',
  'SpVgg Greuther Fürth': '菲尔特',
  'Fortuna Düsseldorf': '杜塞尔多夫',
  'Düsseldorf': '杜塞尔多夫',
  'Hannover 96': '汉诺威96',
  'Hannover': '汉诺威96',
  'FC Nürnberg': '纽伦堡',
  'Nürnberg': '纽伦堡',
  'Hamburger SV': '汉堡',
  'Hamburg': '汉堡',
  'HSV': '汉堡',
  'SC Paderborn 07': '帕德博恩',
  'Paderborn': '帕德博恩',
  'Heidenheim': '海登海姆',
  'FC Heidenheim': '海登海姆',
  'Darmstadt': '达姆施塔特',
  'SV Darmstadt 98': '达姆施塔特',

  // ========== 西甲 La Liga ==========
  'Real Madrid': '皇家马德里',
  'Real Madrid CF': '皇家马德里',
  'Barcelona': '巴塞罗那',
  'FC Barcelona': '巴塞罗那',
  'Atlético Madrid': '马德里竞技',
  'Atlético de Madrid': '马德里竞技',
  'Atletico Madrid': '马德里竞技',
  'Athletic Bilbao': '毕尔巴鄂竞技',
  'Athletic Club': '毕尔巴鄂竞技',
  'Real Sociedad': '皇家社会',
  'Real Betis': '皇家贝蒂斯',
  'Betis': '皇家贝蒂斯',
  'Villarreal': '比利亚雷亚尔',
  'Villarreal CF': '比利亚雷亚尔',
  'Valencia': '瓦伦西亚',
  'Valencia CF': '瓦伦西亚',
  'Osasuna': '奥萨苏纳',
  'CA Osasuna': '奥萨苏纳',
  'Getafe': '赫塔菲',
  'Getafe CF': '赫塔菲',
  'Sevilla': '塞维利亚',
  'Sevilla FC': '塞维利亚',
  'Girona': '赫罗纳',
  'Girona FC': '赫罗纳',
  'Rayo Vallecano': '巴列卡诺',
  'Rayo': '巴列卡诺',
  'Mallorca': '马略卡',
  'RCD Mallorca': '马略卡',
  'Deportivo Alavés': '阿拉维斯',
  'Alavés': '阿拉维斯',
  'Las Palmas': '拉斯帕尔马斯',
  'UD Las Palmas': '拉斯帕尔马斯',
  'Cádiz': '加的斯',
  'Cadiz': '加的斯',
  'Cádiz CF': '加的斯',
  'Celta Vigo': '塞尔塔',
  'Celta de Vigo': '塞尔塔',
  'Celta': '塞尔塔',
  'Granada': '格拉纳达',
  'Granada CF': '格拉纳达',
  'Almería': '阿尔梅里亚',
  'Almeria': '阿尔梅里亚',
  'UD Almería': '阿尔梅里亚',
  'Espanyol': '西班牙人',
  'RCD Espanyol': '西班牙人',
  'Elche': '埃尔切',
  'Elche CF': '埃尔切',
  'Levante': '莱万特',
  'Levante UD': '莱万特',
  'Eibar': '埃瓦尔',
  'SD Eibar': '埃瓦尔',
  'Valladolid': '巴拉多利德',
  'Real Valladolid': '巴拉多利德',
  'Deportivo La Coruña': '拉科鲁尼亚',
  'Deportivo': '拉科鲁尼亚',
  'Huesca': '韦斯卡',
  'SD Huesca': '韦斯卡',
  'Leganés': '莱加内斯',
  'Leganes': '莱加内斯',
  'CD Leganés': '莱加内斯',

  // ========== 意甲 Serie A ==========
  'Inter': '国际米兰',
  'Internazionale': '国际米兰',
  'Inter Milan': '国际米兰',
  'FC Internazionale Milano': '国际米兰',
  'AC Milan': 'AC米兰',
  'Milan': 'AC米兰',
  'Juventus': '尤文图斯',
  'Juventus FC': '尤文图斯',
  'Juve': '尤文图斯',
  'Atalanta': '亚特兰大',
  'Atalanta BC': '亚特兰大',
  'Roma': '罗马',
  'AS Roma': '罗马',
  'AS Rome': '罗马',
  'Lazio': '拉齐奥',
  'SS Lazio': '拉齐奥',
  'Fiorentina': '佛罗伦萨',
  'ACF Fiorentina': '佛罗伦萨',
  'Torino': '都灵',
  'Torino FC': '都灵',
  'Napoli': '那不勒斯',
  'SSC Napoli': '那不勒斯',
  'Napoli FC': '那不勒斯',
  'Bologna': '博洛尼亚',
  'Bologna FC': '博洛尼亚',
  'Frosinone': '弗罗西诺内',
  'Frosinone Calcio': '弗罗西诺内',
  'Sassuolo': '萨索洛',
  'US Sassuolo': '萨索洛',
  'Lecce': '莱切',
  'US Lecce': '莱切',
  'Udinese': '乌迪内斯',
  'Udinese Calcio': '乌迪内斯',
  'Genoa': '热那亚',
  'Genoa CFC': '热那亚',
  'Monza': '蒙扎',
  'AC Monza': '蒙扎',
  'Verona': '维罗纳',
  'Hellas Verona': '维罗纳',
  'Cagliari': '卡利亚里',
  'Cagliari Calcio': '卡利亚里',
  'Empoli': '恩波利',
  'Empoli FC': '恩波利',
  'Salernitana': '萨勒尼塔纳',
  'US Salernitana': '萨勒尼塔纳',
  'Sampdoria': '桑普多利亚',
  'UC Sampdoria': '桑普多利亚',
  'Spezia': '斯佩齐亚',
  'Spezia Calcio': '斯佩齐亚',
  'Cremonese': '克雷莫纳',
  'US Cremonese': '克雷莫纳',
  'Parma': '帕尔马',
  'Parma Calcio': '帕尔马',
  'Benevento': '贝内文托',
  'Benevento Calcio': '贝内文托',
  'Crotone': '克罗托内',
  'FC Crotone': '克罗托内',
  'Chievo': '切沃',
  'Chievo Verona': '切沃',
  'Palermo': '巴勒莫',
  'US Palermo': '巴勒莫',
  'Brescia': '布雷西亚',
  'Brescia Calcio': '布雷西亚',
  'SPAL': '斯帕尔',
  'SPAL 2013': '斯帕尔',

  // ========== 法甲 Ligue 1 ==========
  'Paris Saint-Germain': '巴黎圣日耳曼',
  'Paris SG': '巴黎圣日耳曼',
  'PSG': '巴黎圣日耳曼',
  'AS Monaco': '摩纳哥',
  'Monaco': '摩纳哥',
  'Lille': '里尔',
  'Lille OSC': '里尔',
  'LOSC Lille': '里尔',
  'Olympique Marseille': '马赛',
  'Marseille': '马赛',
  'OM': '马赛',
  'Lens': '朗斯',
  'RC Lens': '朗斯',
  'Rennes': '雷恩',
  'Stade Rennais': '雷恩',
  'Stade Rennes': '雷恩',
  'Nice': '尼斯',
  'OGC Nice': '尼斯',
  'Lyon': '里昂',
  'Olympique Lyon': '里昂',
  'Olympique Lyonnais': '里昂',
  'OL': '里昂',
  'Montpellier': '蒙彼利埃',
  'Montpellier HSC': '蒙彼利埃',
  'Strasbourg': '斯特拉斯堡',
  'RC Strasbourg': '斯特拉斯堡',
  'Reims': '兰斯',
  'Stade de Reims': '兰斯',
  'Toulouse': '图卢兹',
  'Toulouse FC': '图卢兹',
  'Nantes': '南特',
  'FC Nantes': '南特',
  'Lorient': '洛里昂',
  'FC Lorient': '洛里昂',
  'Le Havre': '勒阿弗尔',
  'Le Havre AC': '勒阿弗尔',
  'Brest': '布雷斯特',
  'Stade Brest': '布雷斯特',
  'Stade Brestois': '布雷斯特',
  'Clermont Foot': '克莱蒙',
  'Clermont': '克莱蒙',
  'Metz': '梅斯',
  'FC Metz': '梅斯',
  'Troyes': '特鲁瓦',
  'ESTAC Troyes': '特鲁瓦',
  'Auxerre': '欧塞尔',
  'AJ Auxerre': '欧塞尔',
  'Ajaccio': '阿雅克肖',
  'AC Ajaccio': '阿雅克肖',
  'Angers': '昂热',
  'Angers SCO': '昂热',
  'Saint-Étienne': '圣埃蒂安',
  'Saint-Etienne': '圣埃蒂安',
  'AS Saint-Étienne': '圣埃蒂安',
  'ASSE': '圣埃蒂安',
  'Bordeaux': '波尔多',
  'FC Girondins Bordeaux': '波尔多',
  'Girondins Bordeaux': '波尔多',
  'Nîmes': '尼姆',
  'Nimes': '尼姆',
  'Nîmes Olympique': '尼姆',
  'Dijon': '第戎',
  'Dijon FCO': '第戎',
  'Amiens': '亚眠',
  'Amiens SC': '亚眠',
  'Guingamp': '甘冈',
  'EA Guingamp': '甘冈',
  'Caen': '卡昂',
  'SM Caen': '卡昂',
};

/**
 * 关键词匹配规则
 * 只要队名包含这些关键词，就映射到对应的中文名
 */
const keywordMap = {
  // 英超
  'Manchester City': '曼城',
  'Man City': '曼城',
  'Arsenal': '阿森纳',
  'Liverpool': '利物浦',
  'Aston Villa': '阿斯顿维拉',
  'Tottenham': '托特纳姆热刺',
  'Manchester United': '曼联',
  'Man United': '曼联',
  'Man Utd': '曼联',
  'West Ham': '西汉姆联',
  'Chelsea': '切尔西',
  'Newcastle': '纽卡斯尔联',
  'Brighton': '布莱顿',
  'Wolverhampton': '狼队',
  'Wolves': '狼队',
  'Fulham': '富勒姆',
  'Bournemouth': '伯恩茅斯',
  'Crystal Palace': '水晶宫',
  'Brentford': '布伦特福德',
  'Everton': '埃弗顿',
  'Nottingham': '诺丁汉森林',
  'Luton': '卢顿',
  'Burnley': '伯恩利',
  'Sheffield United': '谢菲尔德联',
  'Sheffield Utd': '谢菲尔德联',
  'Leicester': '莱斯特城',
  'Leeds': '利兹联',
  'Southampton': '南安普顿',
  'Watford': '沃特福德',
  'Norwich': '诺维奇',
  'Ipswich': '伊普斯维奇',
  'Queens Park': '女王公园巡游者',
  'QPR': '女王公园巡游者',
  'Reading': '雷丁',
  'Stoke': '斯托克城',
  'Swansea': '斯旺西',
  'West Brom': '西布罗姆维奇',
  'Huddersfield': '哈德斯菲尔德',
  'Cardiff': '卡迪夫城',
  'Middlesbrough': '米德尔斯堡',
  'Sunderland': '桑德兰',
  'Hull': '赫尔城',
  'Blackburn': '布莱克本',
  'Bolton': '博尔顿',
  'Wigan': '维冈竞技',
  'Portsmouth': '朴茨茅斯',
  
  // 德甲
  'Bayern': '拜仁慕尼黑',
  'Dortmund': '多特蒙德',
  'Leipzig': '莱比锡红牛',
  'Union Berlin': '柏林联合',
  'Freiburg': '弗赖堡',
  'Leverkusen': '勒沃库森',
  'Frankfurt': '法兰克福',
  'Wolfsburg': '沃尔夫斯堡',
  'Mainz': '美因茨',
  'Gladbach': '门兴格拉德巴赫',
  'Köln': '科隆',
  'Cologne': '科隆',
  'Hoffenheim': '霍芬海姆',
  'Bremen': '云达不莱梅',
  'Bochum': '波鸿',
  'Augsburg': '奥格斯堡',
  'Stuttgart': '斯图加特',
  'Hertha': '柏林赫塔',
  'Schalke': '沙尔克04',
  'Bielefeld': '比勒费尔德',
  'Fürth': '菲尔特',
  'Düsseldorf': '杜塞尔多夫',
  'Hannover': '汉诺威96',
  'Nürnberg': '纽伦堡',
  'Hamburg': '汉堡',
  'Paderborn': '帕德博恩',
  'Heidenheim': '海登海姆',
  'Darmstadt': '达姆施塔特',
  
  // 西甲
  'Real Madrid': '皇家马德里',
  'Barcelona': '巴塞罗那',
  'Atlético': '马德里竞技',
  'Atletico': '马德里竞技',
  'Athletic': '毕尔巴鄂竞技',
  'Sociedad': '皇家社会',
  'Betis': '皇家贝蒂斯',
  'Villarreal': '比利亚雷亚尔',
  'Valencia': '瓦伦西亚',
  'Osasuna': '奥萨苏纳',
  'Getafe': '赫塔菲',
  'Sevilla': '塞维利亚',
  'Girona': '赫罗纳',
  'Rayo': '巴列卡诺',
  'Mallorca': '马略卡',
  'Alavés': '阿拉维斯',
  'Alaves': '阿拉维斯',
  'Las Palmas': '拉斯帕尔马斯',
  'Cádiz': '加的斯',
  'Cadiz': '加的斯',
  'Celta': '塞尔塔',
  'Granada': '格拉纳达',
  'Almería': '阿尔梅里亚',
  'Almeria': '阿尔梅里亚',
  'Espanyol': '西班牙人',
  'Elche': '埃尔切',
  'Levante': '莱万特',
  'Eibar': '埃瓦尔',
  'Valladolid': '巴拉多利德',
  'Deportivo': '拉科鲁尼亚',
  'Huesca': '韦斯卡',
  'Leganés': '莱加内斯',
  'Leganes': '莱加内斯',
  
  // 意甲
  'Inter': '国际米兰',
  'Milan': 'AC米兰',
  'Juventus': '尤文图斯',
  'Atalanta': '亚特兰大',
  'Roma': '罗马',
  'Lazio': '拉齐奥',
  'Fiorentina': '佛罗伦萨',
  'Torino': '都灵',
  'Napoli': '那不勒斯',
  'Bologna': '博洛尼亚',
  'Frosinone': '弗罗西诺内',
  'Sassuolo': '萨索洛',
  'Lecce': '莱切',
  'Udinese': '乌迪内斯',
  'Genoa': '热那亚',
  'Monza': '蒙扎',
  'Verona': '维罗纳',
  'Cagliari': '卡利亚里',
  'Empoli': '恩波利',
  'Salernitana': '萨勒尼塔纳',
  'Sampdoria': '桑普多利亚',
  'Spezia': '斯佩齐亚',
  'Cremonese': '克雷莫纳',
  'Parma': '帕尔马',
  'Benevento': '贝内文托',
  'Crotone': '克罗托内',
  'Chievo': '切沃',
  'Palermo': '巴勒莫',
  'Brescia': '布雷西亚',
  'SPAL': '斯帕尔',
  
  // 法甲
  'Paris': '巴黎圣日耳曼',
  'PSG': '巴黎圣日耳曼',
  'Monaco': '摩纳哥',
  'Lille': '里尔',
  'Marseille': '马赛',
  'Lens': '朗斯',
  'Rennes': '雷恩',
  'Nice': '尼斯',
  'Lyon': '里昂',
  'Montpellier': '蒙彼利埃',
  'Strasbourg': '斯特拉斯堡',
  'Reims': '兰斯',
  'Toulouse': '图卢兹',
  'Nantes': '南特',
  'Lorient': '洛里昂',
  'Le Havre': '勒阿弗尔',
  'Brest': '布雷斯特',
  'Clermont': '克莱蒙',
  'Metz': '梅斯',
  'Troyes': '特鲁瓦',
  'Auxerre': '欧塞尔',
  'Ajaccio': '阿雅克肖',
  'Angers': '昂热',
  'Saint-Étienne': '圣埃蒂安',
  'Saint-Etienne': '圣埃蒂安',
  'Bordeaux': '波尔多',
  'Nîmes': '尼姆',
  'Nimes': '尼姆',
  'Dijon': '第戎',
  'Amiens': '亚眠',
  'Guingamp': '甘冈',
  'Caen': '卡昂',
};

/**
 * 将英文球队名翻译为中文
 * @param {string} englishName - 英文球队名
 * @returns {string} - 中文球队名（如果映射表中没有，返回原英文名）
 */
function translateTeamName(englishName) {
  if (!englishName) return '';
  
  // 1. 先尝试完全匹配
  if (teamNameMap[englishName]) {
    return teamNameMap[englishName];
  }
  
  // 2. 尝试去除多余空格后匹配
  const trimmedName = englishName.trim();
  if (teamNameMap[trimmedName]) {
    return teamNameMap[trimmedName];
  }
  
  // 3. 模糊匹配：遍历关键词映射表
  // 按关键词长度降序排列，优先匹配长关键词（更精确）
  const keywords = Object.keys(keywordMap).sort((a, b) => b.length - a.length);
  
  for (const keyword of keywords) {
    // 使用正则表达式进行不区分大小写的匹配
    const regex = new RegExp(keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    if (regex.test(englishName)) {
      return keywordMap[keyword];
    }
  }
  
  // 4. 如果没有找到任何匹配，返回原英文名
  return englishName;
}

/**
 * 批量翻译球队名
 * @param {Array} teams - 球队列表（每个球队对象需要有 team 属性）
 * @returns {Array} - 翻译后的球队列表
 */
function translateTeams(teams) {
  if (!Array.isArray(teams)) return teams;
  
  return teams.map(team => ({
    ...team,
    team: translateTeamName(team.team),
    originalName: team.team // 保留原始英文名
  }));
}

/**
 * 检查是否有缺失的翻译
 * @param {Array} teams - 球队列表
 * @returns {Array} - 缺失翻译的球队名列表
 */
function checkMissingTranslations(teams) {
  if (!Array.isArray(teams)) return [];
  
  const missing = [];
  teams.forEach(team => {
    const name = team.team || team;
    if (typeof name === 'string' && !teamNameMap[name]) {
      if (!missing.includes(name)) {
        missing.push(name);
      }
    }
  });
  
  return missing;
}

module.exports = {
  teamNameMap,
  translateTeamName,
  translateTeams,
  checkMissingTranslations
};
